### ISSUE TITLE
Running on linux fails due to pyreadline3

### ISSUE THREAD

**Issue by ShaddyDC** [efJerryYang/chatgpt-cli#26] opened 2023-05-21 09:07 UTC
Hi, I was trying to use this package on Linux, specifically NixOS.
If the project is built with the pyreadline3 package, it fails at runtime because it's trying to use some windows functionality.
Without the package, the project fails to build.
With the dependency checks removed, it builds and works just fine because it's a drop-in replacement as discussed in #6.

Technically, this is an issue in both the requirements.txt file and the pyproject.toml file, but on NixOS there's mechanisms to easily work around requirements.txt.
I would first suggest changing the pyproject.toml file like described [here](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies), which fixes the issue for me:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 131cdec..5b17b0e 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -21,7 +21,7 @@ classifiers = [
   "Operating System :: OS Independent",
 ]
 scripts = { chatgpt-cli = "chatgpt_cli.chat:main" }
-dependencies = ["openai >= 0.27.0", "pyyaml >= 6.0", "rich >= 13.3.1", "pyreadline3 >= 3.4.1"]
+dependencies = ["openai >= 0.27.0", "pyyaml >= 6.0", "rich >= 13.3.1", "pyreadline3 >= 3.4.1; platform_system=='Windows'"]
 
 [build-system]
 requires = ["setuptools>=61.0", "wheel"]
```

There appear to be similar ways to work around the [requirements.txt file](https://stackoverflow.com/questions/29222269/is-there-a-way-to-have-a-conditional-requirements-txt-file-for-my-python-applica/35614580#35614580), but I have not looked into them.

Edit: 

I noticed another issue say that pyreadline3 is supposed to support linux too, so I figured I'd provde the runtime error I'm getting.

<details>
  <summary>Error</summary>

  ```
  Traceback (most recent call last):
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/pyreadline3/keysyms/__init__.py", line 15, in <module>
      from .keysyms import *
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/pyreadline3/keysyms/keysyms.py", line 13, in <module>
      from ctypes import windll
  ImportError: cannot import name 'windll' from 'ctypes' (/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/ctypes/__init__.py)
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/pyreadline3/console/__init__.py", line 14, in <module>
      from .console import *
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/pyreadline3/console/console.py", line 28, in <module>
      from pyreadline3.keysyms import KeyPress, make_KeyPress
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/pyreadline3/keysyms/__init__.py", line 17, in <module>
      raise ImportError(
  ImportError: Could not import keysym for local python version
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/nix/store/9f9rbfvfrp3skwahazryvn10av8yrkj8-chatgpt-cli-v0.1.13/bin/.chatgpt-cli-wrapped", line 6, in <module>
      from chatgpt_cli.chat import main
    File "/nix/store/9f9rbfvfrp3skwahazryvn10av8yrkj8-chatgpt-cli-v0.1.13/lib/python3.10/site-packages/chatgpt_cli/chat.py", line 4, in <module>
      from chatgpt_cli.conversation import generate_response
    File "/nix/store/9f9rbfvfrp3skwahazryvn10av8yrkj8-chatgpt-cli-v0.1.13/lib/python3.10/site-packages/chatgpt_cli/conversation.py", line 7, in <module>
      from utils.file import *
    File "/nix/store/9f9rbfvfrp3skwahazryvn10av8yrkj8-chatgpt-cli-v0.1.13/lib/python3.10/site-packages/utils/file.py", line 7, in <module>
      from utils.io import *
    File "/nix/store/9f9rbfvfrp3skwahazryvn10av8yrkj8-chatgpt-cli-v0.1.13/lib/python3.10/site-packages/utils/io.py", line 4, in <module>
      import readline
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/readline.py", line 7, in <module>
      from pyreadline3.rlmain import Readline
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/pyreadline3/__init__.py", line 14, in <module>
      from . import (
    File "/nix/store/rkmj4vxx7861adb3x3m1gqy34c53x25i-python3.10-pyreadline3-3.4.1/lib/python3.10/site-packages/pyreadline3/console/__init__.py", line 16, in <module>
      raise ImportError(
  ImportError: Could not find a console implementation for local python version
  ```
</details>

**Comment by efJerryYang** [comment] 2023-05-21 09:34
Thanks for mentioning this problem, it seems strange as the package `pyreadline3` is supposed to be working on Linux (tested on kubuntu 22.10), but it failed on your OS actually. I am really busy these days and it may truly take some time to reproduce this issue (like creating a NixOS VM to figure out the cause), so I tend to take your solution directly later when I have time (maybe tomorrow).

I will close this issue when I update the `requirements.txt` and `pyproject.toml`, and test this build in an isolated environment on my machine and on Windows.

**Comment by efJerryYang** [comment] 2023-05-21 09:35
> > I would first suggest changing the pyproject.toml file like described [here](https://github.com/efJerryYang/chatgpt-cli/issues/setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies), which fixes the issue for me:
> 
> The link you provided here seems to be broken, would you like to update it with a new one?

I found the site [here](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies), thanks for your suggestion.

**Comment by ShaddyDC** [comment] 2023-05-21 09:39
Oops, sorry, link should be fixed!
I'll be happy to provide a complete nix derivation (effectively a nix build script) for reproduction purposes once I've got something I'm happy with.

**Comment by efJerryYang** [comment] 2023-05-21 09:43
Haha, thank you, I can manage it when I have time to do so (I have often thought of using Nix as the package manager). I am just swamped at the moment.

**Comment by ShaddyDC** [comment] 2023-05-21 09:44
Npnp, if it should otherwise work, I'll also see if it works if I build pyreadline3 from source on nix. I'll report back in like half an hour.

**Comment by efJerryYang** [comment] 2023-05-21 09:51
If you're willing to give it a try, I would appreciate it. In fact, your previous solution was already great because the purpose of introducing `pyreadline3` was to address the compatibility of this tool on Windows. Linux already has native python `readline` support, so it is also acceptable to differentiate the build based on the operating system from the beginning :+1:

**Comment by ShaddyDC** [comment] 2023-05-21 10:06
That sounds good to me!
I can also confirm that building `pyreadline3` like this:
```nix
"pyreadline3" = python.pkgs.buildPythonPackage rec {
  pname = "pyreadline3";
  version = "3.4.1";
  src = pkgs.fetchPypi {
    inherit pname version;
    sha256 = "sha256-bz0fe4oxujK3ORfO/B8ozGYFYvOa6oZG0wvW7/Ife64=";
  };
  doCheck = false;
  buildInputs = [];
  checkInputs = [];

  propagatedBuildInputs = with python.pkgs; [
  ];
};
```
Fails with the error:
```
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "/build/pyreadline3-3.4.1/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 19, in <module>
    raise RuntimeError('pyreadline3 is for Windows only, not {}.'.format(_S))
RuntimeError: pyreadline3 is for Windows only, not Linux.
/nix/store/37p8gq9zijbw6pj3lpi1ckqiv18j2g62-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
```

In case this is of interest to anybody else, that leaves me with a working derivation of

<details>
  <summary>Spoiler warning</summary>
  
 ```nix
python = pkgs.python3;

mdformat-footnote = python.pkgs.buildPythonPackage rec {
  pname = "mdformat-footnote";
  version = "0.1.1";
  src = pkgs.fetchFromGitHub {
    owner = "executablebooks";
    repo = pname;
    rev = "v${version}";
    sha256 = "sha256-DUCBWcmB5i6/HkqxjlU3aTRO7i0n2sj+e/doKB8ffeo=";
  };
  format = "pyproject";
  doCheck = false;
  buildInputs = [];
  checkInputs = [];
  nativeBuildInputs = [];
  propagatedBuildInputs = with python.pkgs; [
    mdformat
    mdit-py-plugins
    flit
  ];
};
mdformat-frontmatter = python.pkgs.buildPythonPackage rec {
  pname = "mdformat-frontmatter";
  version = "2.0.1";
  src = pkgs.fetchFromGitHub {
    owner = "butler54";
    repo = pname;
    rev = "v${version}";
    sha256 = "sha256-PhT5whtvvcYSs5gHQEsIvV1evhx7jR+3DWFMHrF0uMw=";
  };

  format = "pyproject";
  doCheck = false;
  buildInputs = [];
  checkInputs = [];
  nativeBuildInputs = [];
  propagatedBuildInputs = with python.pkgs; [
    mdformat
    mdit-py-plugins
    ruamel-yaml
    flit
  ];
};
mdformat-tables = python.pkgs.buildPythonPackage rec {
  pname = "mdformat-tables";
  version = "0.4.1";
  src = pkgs.fetchFromGitHub {
    owner = "executablebooks";
    repo = pname;
    rev = "v${version}";
    sha256 = "sha256-Q61GmaRxjxJh9GjyR8QCZOH0njFUtAWihZ9lFQJ2nQQ=";
  };
  format = "pyproject";
  doCheck = false;
  buildInputs = [];
  checkInputs = [];
  nativeBuildInputs = [];
  propagatedBuildInputs = with python.pkgs; [
    mdformat
    flit
  ];
};
mdformat-gfm = python.pkgs.buildPythonPackage rec {
  pname = "mdformat-gfm";
  version = "0.3.5";
  src = pkgs.fetchPypi {
    inherit pname version;
    sha256 = "sha256-XuXw3h07VtXt/O0CO//wru2Vi+Mo5UYNrDIhrBthznw=";
  };
  format = "pyproject";
  doCheck = false;
  buildInputs = [];
  checkInputs = [];
  nativeBuildInputs = [python.pkgs.pythonRelaxDepsHook];
  pythonRemoveDeps = ["markdown-it-py"];

  propagatedBuildInputs = with python.pkgs; [
    markdown-it-py
    mdformat
    mdformat-tables
    mdit-py-plugins
    poetry-core
  ];
};
mdit-py-plugins = python.pkgs.buildPythonPackage rec {
  pname = "mdit-py-plugins";
  version = "0.3.5";
  src = pkgs.fetchPypi {
    inherit pname version;
    sha256 = "sha256-7uCtxxleWCfhfgLSoliiuhWZRKB0j1nFCZpKJ/ePz2o=";
  };
  format = "pyproject";
  doCheck = false;
  buildInputs = [];
  checkInputs = [];
  nativeBuildInputs = [];
  propagatedBuildInputs = with python.pkgs; [
    markdown-it-py
    flit
  ];
};

pk = with python.pkgs;
  buildPythonApplication {
    pname = "chatgpt-cli";
    version = "v0.1.13";

    format = "pyproject";

    nativeBuildInputs = [python.pkgs.pythonRelaxDepsHook];
    pythonRemoveDeps = ["pyreadline3"];

    propagatedBuildInputs = [
      setuptools

      aiohttp
      aiosignal
      async-timeout
      attrs
      black
      certifi
      charset-normalizer
      click
      frozenlist
      idna
      markdown-it-py
      mdformat
      mdformat-gfm
      mdformat-frontmatter
      mdformat-footnote
      mdurl
      multidict
      mypy-extensions
      openai
      packaging
      pathspec
      platformdirs
      pygments
      pyyaml
      requests
      rich
      tomli
      tqdm
      urllib3
      yarl
    ];

    src = ./.;

    postPatch = ''
      substituteInPlace pyproject.toml \
        --replace ', "pyreadline3 >= 3.4.1"' ""
    '';
  };
```
  
</details>

**Comment by efJerryYang** [comment] 2023-05-21 10:56
Thanks for your efforts!

**Closed as completed** 2023-05-29 07:42 UTC
